name: Clean

on:
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  check-need-info:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.mytoken }}
          exclude-labels: 'pin'
          body: '超过7天暂时没时间处理，关闭issue'
          inactive-day: 7